Update syntax highlighting for Emacs
tsoding/Noq pull request #2
Opened 2022-04-11 04:28 UTC by Piturnah

Since the most recent stream was dedicated to bikeshedding the syntax, I've updated the noq-mode.el to reflect the changes!

![image](https://user-images.githubusercontent.com/20472367/162664833-37bff3ac-8a20-44f1-9e19-469fa9faa3c4.png)
![image](https://user-images.githubusercontent.com/20472367/162665081-03bf6a5c-0dfd-4d36-b888-03e7195e1831.png)

Hope you like it!

2022-04-11 04:35 UTC, Piturnah commented
Note the comment on line 57:
```elisp
    ;; FIXME: It would be cool if variables were highlighted too (see below). However, there is an
    ;; issue in that a number can either be a symbol or a variable depending on the context.
    ;; The regex below works around this by only highlighting variables that don't start with a
    ;; number, however this obviously won't cover all possible variables.
```
In the end, I left the regex rule uncommented, as looking through all of the provided examples and standard library there wasn't any cases where this applied. However, it's still worth noting, and worth considering removing, in my opinion

2022-04-11 14:46 UTC, rexim commented
> However, there is an issue in that a number can either be a symbol or a variable depending on the context

No, number is always a symbol. Variable is any identifier that starts with a capital letter or an underscore `_`: https://github.com/tsoding/Noq/blob/62d9e6d4408524657abe3bf1e27e8eeeb22722a6/src/main.rs#L196-L203

2022-04-11 14:48 UTC, rexim requested changes

2022-04-11 14:48 UTC, rexim commented on editor/noq-mode.el
> -    '("rule" "shape" "apply" "done" "quit" "undo" "reverse" "load")))
`undo`, `quit`, `delete` and `load` are still actively used keywords:

https://github.com/tsoding/Noq/blob/62d9e6d4408524657abe3bf1e27e8eeeb22722a6/src/lexer.rs#L35-L39

2022-04-12 13:21 UTC, rexim commented
I don't know why but variables are not highlighted for me:

![2022-04-12-201929_912x858_scrot](https://user-images.githubusercontent.com/165283/162971708-ab9c2ed4-507d-4176-a73f-8e9d71b2c285.png)

Commit: 287e5316dfe1f0baafcfa548c5adb9bab6e8c94d
Version: GNU Emacs 27.1

2022-04-12 14:43 UTC, Piturnah commented
I suspect this is because gruber-darker doesn't define highlighting for variables, you can see with `M-x list-faces-display` under `font-lock-variable-name-face`. It shows on most other themes, I changed to this face in commit 701eaed since I thought it would match the semantic better

Before it was using `font-lock-builtin-face`

2022-04-12 16:55 UTC, rexim commented
@Piturnah oh I see, it uses a color that is almost indistinguishable from the foreground: 

https://github.com/rexim/gruber-darker-theme/blob/72278089c440d45c00fb8afcd53af82fd30f451b/gruber-darker-theme.el#L186

Thanks for the explanation! And thanks for the contribution!

2022-04-12 16:55 UTC, rexim approved these changes

2022-04-12 16:55 UTC, merged